./magnapp_cli_linux64 -G ../Data2/Bothriolepis.txt -H ../Data2/Actinolepis.txt -o ../Results/BothriolepisActinolepis -d ../Results/BothriolepisActinolepis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Actinolepis.txt -H ../Data2/Brindabellaspis.txt -o ../Results/BrindabellaspisActinolepis -d ../Results/BrindabellaspisActinolepis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Buchanosteus.txt -H ../Data2/Actinolepis.txt -o ../Results/BuchanosteusActinolepis -d ../Results/BuchanosteusActinolepis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Actinolepis.txt -H ../Data2/Cheirolepis.txt -o ../Results/CheirolepisActinolepis -d ../Results/CheirolepisActinolepis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Cowralepis.txt -H ../Data2/Actinolepis.txt -o ../Results/CowralepisActinolepis -d ../Results/CowralepisActinolepis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Dialipina.txt -H ../Data2/Actinolepis.txt -o ../Results/DialipinaActinolepis -d ../Results/DialipinaActinolepis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Diandongpetalichthys.txt -H ../Data2/Actinolepis.txt -o ../Results/DiandongpetalichthysActinolepis -d ../Results/DiandongpetalichthysActinolepis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Actinolepis.txt -H ../Data2/Dicksonosteus.txt -o ../Results/DicksonosteusActinolepis -d ../Results/DicksonosteusActinolepis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Entelognathus.txt -H ../Data2/Actinolepis.txt -o ../Results/EntelognathusActinolepis -d ../Results/EntelognathusActinolepis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Eurycaraspis.txt -H ../Data2/Actinolepis.txt -o ../Results/EurycaraspisActinolepis -d ../Results/EurycaraspisActinolepis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Actinolepis.txt -H ../Data2/Eusthenopteron.txt -o ../Results/EusthenopteronActinolepis -d ../Results/EusthenopteronActinolepis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Actinolepis.txt -H ../Data2/Guiyu.txt -o ../Results/GuiyuActinolepis -d ../Results/GuiyuActinolepis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Lunaspis.txt -H ../Data2/Actinolepis.txt -o ../Results/LunaspisActinolepis -d ../Results/LunaspisActinolepis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Meemannia.txt -H ../Data2/Actinolepis.txt -o ../Results/MeemanniaActinolepis -d ../Results/MeemanniaActinolepis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Actinolepis.txt -H ../Data2/Moythomasia.txt -o ../Results/MoythomasiaActinolepis -d ../Results/MoythomasiaActinolepis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Actinolepis.txt -H ../Data2/Romundina.txt -o ../Results/RomundinaActinolepis -d ../Results/RomundinaActinolepis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Wuttagoonaspis.txt -H ../Data2/Actinolepis.txt -o ../Results/WuttagoonaspisActinolepis -d ../Results/WuttagoonaspisActinolepis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Bothriolepis.txt -H ../Data2/Brindabellaspis.txt -o ../Results/BrindabellaspisBothriolepis -d ../Results/BrindabellaspisBothriolepis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Buchanosteus.txt -H ../Data2/Bothriolepis.txt -o ../Results/BuchanosteusBothriolepis -d ../Results/BuchanosteusBothriolepis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Bothriolepis.txt -H ../Data2/Cheirolepis.txt -o ../Results/CheirolepisBothriolepis -d ../Results/CheirolepisBothriolepis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Cowralepis.txt -H ../Data2/Bothriolepis.txt -o ../Results/CowralepisBothriolepis -d ../Results/CowralepisBothriolepis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Dialipina.txt -H ../Data2/Bothriolepis.txt -o ../Results/DialipinaBothriolepis -d ../Results/DialipinaBothriolepis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Diandongpetalichthys.txt -H ../Data2/Bothriolepis.txt -o ../Results/DiandongpetalichthysBothriolepis -d ../Results/DiandongpetalichthysBothriolepis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Bothriolepis.txt -H ../Data2/Dicksonosteus.txt -o ../Results/DicksonosteusBothriolepis -d ../Results/DicksonosteusBothriolepis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Bothriolepis.txt -H ../Data2/Entelognathus.txt -o ../Results/EntelognathusBothriolepis -d ../Results/EntelognathusBothriolepis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Bothriolepis.txt -H ../Data2/Eurycaraspis.txt -o ../Results/EurycaraspisBothriolepis -d ../Results/EurycaraspisBothriolepis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Bothriolepis.txt -H ../Data2/Eusthenopteron.txt -o ../Results/EusthenopteronBothriolepis -d ../Results/EusthenopteronBothriolepis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Bothriolepis.txt -H ../Data2/Guiyu.txt -o ../Results/GuiyuBothriolepis -d ../Results/GuiyuBothriolepis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Bothriolepis.txt -H ../Data2/Lunaspis.txt -o ../Results/LunaspisBothriolepis -d ../Results/LunaspisBothriolepis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Meemannia.txt -H ../Data2/Bothriolepis.txt -o ../Results/MeemanniaBothriolepis -d ../Results/MeemanniaBothriolepis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Bothriolepis.txt -H ../Data2/Moythomasia.txt -o ../Results/MoythomasiaBothriolepis -d ../Results/MoythomasiaBothriolepis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Bothriolepis.txt -H ../Data2/Romundina.txt -o ../Results/RomundinaBothriolepis -d ../Results/RomundinaBothriolepis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Wuttagoonaspis.txt -H ../Data2/Bothriolepis.txt -o ../Results/WuttagoonaspisBothriolepis -d ../Results/WuttagoonaspisBothriolepis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Buchanosteus.txt -H ../Data2/Brindabellaspis.txt -o ../Results/BuchanosteusBrindabellaspis -d ../Results/BuchanosteusBrindabellaspis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Cheirolepis.txt -H ../Data2/Brindabellaspis.txt -o ../Results/CheirolepisBrindabellaspis -d ../Results/CheirolepisBrindabellaspis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Cowralepis.txt -H ../Data2/Brindabellaspis.txt -o ../Results/CowralepisBrindabellaspis -d ../Results/CowralepisBrindabellaspis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Dialipina.txt -H ../Data2/Brindabellaspis.txt -o ../Results/DialipinaBrindabellaspis -d ../Results/DialipinaBrindabellaspis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Diandongpetalichthys.txt -H ../Data2/Brindabellaspis.txt -o ../Results/DiandongpetalichthysBrindabellaspis -d ../Results/DiandongpetalichthysBrindabellaspis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Dicksonosteus.txt -H ../Data2/Brindabellaspis.txt -o ../Results/DicksonosteusBrindabellaspis -d ../Results/DicksonosteusBrindabellaspis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Entelognathus.txt -H ../Data2/Brindabellaspis.txt -o ../Results/EntelognathusBrindabellaspis -d ../Results/EntelognathusBrindabellaspis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Eurycaraspis.txt -H ../Data2/Brindabellaspis.txt -o ../Results/EurycaraspisBrindabellaspis -d ../Results/EurycaraspisBrindabellaspis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Eusthenopteron.txt -H ../Data2/Brindabellaspis.txt -o ../Results/EusthenopteronBrindabellaspis -d ../Results/EusthenopteronBrindabellaspis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Brindabellaspis.txt -H ../Data2/Guiyu.txt -o ../Results/GuiyuBrindabellaspis -d ../Results/GuiyuBrindabellaspis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Lunaspis.txt -H ../Data2/Brindabellaspis.txt -o ../Results/LunaspisBrindabellaspis -d ../Results/LunaspisBrindabellaspis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Meemannia.txt -H ../Data2/Brindabellaspis.txt -o ../Results/MeemanniaBrindabellaspis -d ../Results/MeemanniaBrindabellaspis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Moythomasia.txt -H ../Data2/Brindabellaspis.txt -o ../Results/MoythomasiaBrindabellaspis -d ../Results/MoythomasiaBrindabellaspis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Romundina.txt -H ../Data2/Brindabellaspis.txt -o ../Results/RomundinaBrindabellaspis -d ../Results/RomundinaBrindabellaspis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Wuttagoonaspis.txt -H ../Data2/Brindabellaspis.txt -o ../Results/WuttagoonaspisBrindabellaspis -d ../Results/WuttagoonaspisBrindabellaspis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Buchanosteus.txt -H ../Data2/Cheirolepis.txt -o ../Results/CheirolepisBuchanosteus -d ../Results/CheirolepisBuchanosteus.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Cowralepis.txt -H ../Data2/Buchanosteus.txt -o ../Results/CowralepisBuchanosteus -d ../Results/CowralepisBuchanosteus.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Dialipina.txt -H ../Data2/Buchanosteus.txt -o ../Results/DialipinaBuchanosteus -d ../Results/DialipinaBuchanosteus.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Diandongpetalichthys.txt -H ../Data2/Buchanosteus.txt -o ../Results/DiandongpetalichthysBuchanosteus -d ../Results/DiandongpetalichthysBuchanosteus.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Buchanosteus.txt -H ../Data2/Dicksonosteus.txt -o ../Results/DicksonosteusBuchanosteus -d ../Results/DicksonosteusBuchanosteus.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Buchanosteus.txt -H ../Data2/Entelognathus.txt -o ../Results/EntelognathusBuchanosteus -d ../Results/EntelognathusBuchanosteus.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Buchanosteus.txt -H ../Data2/Eurycaraspis.txt -o ../Results/EurycaraspisBuchanosteus -d ../Results/EurycaraspisBuchanosteus.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Buchanosteus.txt -H ../Data2/Eusthenopteron.txt -o ../Results/EusthenopteronBuchanosteus -d ../Results/EusthenopteronBuchanosteus.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Buchanosteus.txt -H ../Data2/Guiyu.txt -o ../Results/GuiyuBuchanosteus -d ../Results/GuiyuBuchanosteus.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Buchanosteus.txt -H ../Data2/Lunaspis.txt -o ../Results/LunaspisBuchanosteus -d ../Results/LunaspisBuchanosteus.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Meemannia.txt -H ../Data2/Buchanosteus.txt -o ../Results/MeemanniaBuchanosteus -d ../Results/MeemanniaBuchanosteus.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Buchanosteus.txt -H ../Data2/Moythomasia.txt -o ../Results/MoythomasiaBuchanosteus -d ../Results/MoythomasiaBuchanosteus.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Buchanosteus.txt -H ../Data2/Romundina.txt -o ../Results/RomundinaBuchanosteus -d ../Results/RomundinaBuchanosteus.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Wuttagoonaspis.txt -H ../Data2/Buchanosteus.txt -o ../Results/WuttagoonaspisBuchanosteus -d ../Results/WuttagoonaspisBuchanosteus.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Cowralepis.txt -H ../Data2/Cheirolepis.txt -o ../Results/CowralepisCheirolepis -d ../Results/CowralepisCheirolepis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Dialipina.txt -H ../Data2/Cheirolepis.txt -o ../Results/DialipinaCheirolepis -d ../Results/DialipinaCheirolepis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Diandongpetalichthys.txt -H ../Data2/Cheirolepis.txt -o ../Results/DiandongpetalichthysCheirolepis -d ../Results/DiandongpetalichthysCheirolepis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Dicksonosteus.txt -H ../Data2/Cheirolepis.txt -o ../Results/DicksonosteusCheirolepis -d ../Results/DicksonosteusCheirolepis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Entelognathus.txt -H ../Data2/Cheirolepis.txt -o ../Results/EntelognathusCheirolepis -d ../Results/EntelognathusCheirolepis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Eurycaraspis.txt -H ../Data2/Cheirolepis.txt -o ../Results/EurycaraspisCheirolepis -d ../Results/EurycaraspisCheirolepis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Cheirolepis.txt -H ../Data2/Eusthenopteron.txt -o ../Results/EusthenopteronCheirolepis -d ../Results/EusthenopteronCheirolepis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Cheirolepis.txt -H ../Data2/Guiyu.txt -o ../Results/GuiyuCheirolepis -d ../Results/GuiyuCheirolepis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Lunaspis.txt -H ../Data2/Cheirolepis.txt -o ../Results/LunaspisCheirolepis -d ../Results/LunaspisCheirolepis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Meemannia.txt -H ../Data2/Cheirolepis.txt -o ../Results/MeemanniaCheirolepis -d ../Results/MeemanniaCheirolepis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Cheirolepis.txt -H ../Data2/Moythomasia.txt -o ../Results/MoythomasiaCheirolepis -d ../Results/MoythomasiaCheirolepis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Romundina.txt -H ../Data2/Cheirolepis.txt -o ../Results/RomundinaCheirolepis -d ../Results/RomundinaCheirolepis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Wuttagoonaspis.txt -H ../Data2/Cheirolepis.txt -o ../Results/WuttagoonaspisCheirolepis -d ../Results/WuttagoonaspisCheirolepis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Cowralepis.txt -H ../Data2/Dialipina.txt -o ../Results/DialipinaCowralepis -d ../Results/DialipinaCowralepis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Cowralepis.txt -H ../Data2/Diandongpetalichthys.txt -o ../Results/DiandongpetalichthysCowralepis -d ../Results/DiandongpetalichthysCowralepis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Cowralepis.txt -H ../Data2/Dicksonosteus.txt -o ../Results/DicksonosteusCowralepis -d ../Results/DicksonosteusCowralepis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Cowralepis.txt -H ../Data2/Entelognathus.txt -o ../Results/EntelognathusCowralepis -d ../Results/EntelognathusCowralepis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Cowralepis.txt -H ../Data2/Eurycaraspis.txt -o ../Results/EurycaraspisCowralepis -d ../Results/EurycaraspisCowralepis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Cowralepis.txt -H ../Data2/Eusthenopteron.txt -o ../Results/EusthenopteronCowralepis -d ../Results/EusthenopteronCowralepis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Cowralepis.txt -H ../Data2/Guiyu.txt -o ../Results/GuiyuCowralepis -d ../Results/GuiyuCowralepis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Cowralepis.txt -H ../Data2/Lunaspis.txt -o ../Results/LunaspisCowralepis -d ../Results/LunaspisCowralepis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Meemannia.txt -H ../Data2/Cowralepis.txt -o ../Results/MeemanniaCowralepis -d ../Results/MeemanniaCowralepis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Cowralepis.txt -H ../Data2/Moythomasia.txt -o ../Results/MoythomasiaCowralepis -d ../Results/MoythomasiaCowralepis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Cowralepis.txt -H ../Data2/Romundina.txt -o ../Results/RomundinaCowralepis -d ../Results/RomundinaCowralepis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Cowralepis.txt -H ../Data2/Wuttagoonaspis.txt -o ../Results/WuttagoonaspisCowralepis -d ../Results/WuttagoonaspisCowralepis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Dialipina.txt -H ../Data2/Diandongpetalichthys.txt -o ../Results/DiandongpetalichthysDialipina -d ../Results/DiandongpetalichthysDialipina.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Dialipina.txt -H ../Data2/Dicksonosteus.txt -o ../Results/DicksonosteusDialipina -d ../Results/DicksonosteusDialipina.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Dialipina.txt -H ../Data2/Entelognathus.txt -o ../Results/EntelognathusDialipina -d ../Results/EntelognathusDialipina.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Dialipina.txt -H ../Data2/Eurycaraspis.txt -o ../Results/EurycaraspisDialipina -d ../Results/EurycaraspisDialipina.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Dialipina.txt -H ../Data2/Eusthenopteron.txt -o ../Results/EusthenopteronDialipina -d ../Results/EusthenopteronDialipina.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Dialipina.txt -H ../Data2/Guiyu.txt -o ../Results/GuiyuDialipina -d ../Results/GuiyuDialipina.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Dialipina.txt -H ../Data2/Lunaspis.txt -o ../Results/LunaspisDialipina -d ../Results/LunaspisDialipina.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Meemannia.txt -H ../Data2/Dialipina.txt -o ../Results/MeemanniaDialipina -d ../Results/MeemanniaDialipina.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Dialipina.txt -H ../Data2/Moythomasia.txt -o ../Results/MoythomasiaDialipina -d ../Results/MoythomasiaDialipina.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Dialipina.txt -H ../Data2/Romundina.txt -o ../Results/RomundinaDialipina -d ../Results/RomundinaDialipina.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Dialipina.txt -H ../Data2/Wuttagoonaspis.txt -o ../Results/WuttagoonaspisDialipina -d ../Results/WuttagoonaspisDialipina.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Diandongpetalichthys.txt -H ../Data2/Dicksonosteus.txt -o ../Results/DicksonosteusDiandongpetalichthys -d ../Results/DicksonosteusDiandongpetalichthys.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Diandongpetalichthys.txt -H ../Data2/Entelognathus.txt -o ../Results/EntelognathusDiandongpetalichthys -d ../Results/EntelognathusDiandongpetalichthys.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Diandongpetalichthys.txt -H ../Data2/Eurycaraspis.txt -o ../Results/EurycaraspisDiandongpetalichthys -d ../Results/EurycaraspisDiandongpetalichthys.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Diandongpetalichthys.txt -H ../Data2/Eusthenopteron.txt -o ../Results/EusthenopteronDiandongpetalichthys -d ../Results/EusthenopteronDiandongpetalichthys.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Diandongpetalichthys.txt -H ../Data2/Guiyu.txt -o ../Results/GuiyuDiandongpetalichthys -d ../Results/GuiyuDiandongpetalichthys.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Diandongpetalichthys.txt -H ../Data2/Lunaspis.txt -o ../Results/LunaspisDiandongpetalichthys -d ../Results/LunaspisDiandongpetalichthys.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Meemannia.txt -H ../Data2/Diandongpetalichthys.txt -o ../Results/MeemanniaDiandongpetalichthys -d ../Results/MeemanniaDiandongpetalichthys.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Diandongpetalichthys.txt -H ../Data2/Moythomasia.txt -o ../Results/MoythomasiaDiandongpetalichthys -d ../Results/MoythomasiaDiandongpetalichthys.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Diandongpetalichthys.txt -H ../Data2/Romundina.txt -o ../Results/RomundinaDiandongpetalichthys -d ../Results/RomundinaDiandongpetalichthys.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Wuttagoonaspis.txt -H ../Data2/Diandongpetalichthys.txt -o ../Results/WuttagoonaspisDiandongpetalichthys -d ../Results/WuttagoonaspisDiandongpetalichthys.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Entelognathus.txt -H ../Data2/Dicksonosteus.txt -o ../Results/EntelognathusDicksonosteus -d ../Results/EntelognathusDicksonosteus.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Eurycaraspis.txt -H ../Data2/Dicksonosteus.txt -o ../Results/EurycaraspisDicksonosteus -d ../Results/EurycaraspisDicksonosteus.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Dicksonosteus.txt -H ../Data2/Eusthenopteron.txt -o ../Results/EusthenopteronDicksonosteus -d ../Results/EusthenopteronDicksonosteus.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Dicksonosteus.txt -H ../Data2/Guiyu.txt -o ../Results/GuiyuDicksonosteus -d ../Results/GuiyuDicksonosteus.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Lunaspis.txt -H ../Data2/Dicksonosteus.txt -o ../Results/LunaspisDicksonosteus -d ../Results/LunaspisDicksonosteus.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Meemannia.txt -H ../Data2/Dicksonosteus.txt -o ../Results/MeemanniaDicksonosteus -d ../Results/MeemanniaDicksonosteus.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Dicksonosteus.txt -H ../Data2/Moythomasia.txt -o ../Results/MoythomasiaDicksonosteus -d ../Results/MoythomasiaDicksonosteus.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Dicksonosteus.txt -H ../Data2/Romundina.txt -o ../Results/RomundinaDicksonosteus -d ../Results/RomundinaDicksonosteus.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Wuttagoonaspis.txt -H ../Data2/Dicksonosteus.txt -o ../Results/WuttagoonaspisDicksonosteus -d ../Results/WuttagoonaspisDicksonosteus.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Eurycaraspis.txt -H ../Data2/Entelognathus.txt -o ../Results/EurycaraspisEntelognathus -d ../Results/EurycaraspisEntelognathus.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Entelognathus.txt -H ../Data2/Eusthenopteron.txt -o ../Results/EusthenopteronEntelognathus -d ../Results/EusthenopteronEntelognathus.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Entelognathus.txt -H ../Data2/Guiyu.txt -o ../Results/GuiyuEntelognathus -d ../Results/GuiyuEntelognathus.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Lunaspis.txt -H ../Data2/Entelognathus.txt -o ../Results/LunaspisEntelognathus -d ../Results/LunaspisEntelognathus.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Meemannia.txt -H ../Data2/Entelognathus.txt -o ../Results/MeemanniaEntelognathus -d ../Results/MeemanniaEntelognathus.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Entelognathus.txt -H ../Data2/Moythomasia.txt -o ../Results/MoythomasiaEntelognathus -d ../Results/MoythomasiaEntelognathus.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Entelognathus.txt -H ../Data2/Romundina.txt -o ../Results/RomundinaEntelognathus -d ../Results/RomundinaEntelognathus.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Wuttagoonaspis.txt -H ../Data2/Entelognathus.txt -o ../Results/WuttagoonaspisEntelognathus -d ../Results/WuttagoonaspisEntelognathus.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Eurycaraspis.txt -H ../Data2/Eusthenopteron.txt -o ../Results/EusthenopteronEurycaraspis -d ../Results/EusthenopteronEurycaraspis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Eurycaraspis.txt -H ../Data2/Guiyu.txt -o ../Results/GuiyuEurycaraspis -d ../Results/GuiyuEurycaraspis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Lunaspis.txt -H ../Data2/Eurycaraspis.txt -o ../Results/LunaspisEurycaraspis -d ../Results/LunaspisEurycaraspis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Meemannia.txt -H ../Data2/Eurycaraspis.txt -o ../Results/MeemanniaEurycaraspis -d ../Results/MeemanniaEurycaraspis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Eurycaraspis.txt -H ../Data2/Moythomasia.txt -o ../Results/MoythomasiaEurycaraspis -d ../Results/MoythomasiaEurycaraspis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Eurycaraspis.txt -H ../Data2/Romundina.txt -o ../Results/RomundinaEurycaraspis -d ../Results/RomundinaEurycaraspis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Wuttagoonaspis.txt -H ../Data2/Eurycaraspis.txt -o ../Results/WuttagoonaspisEurycaraspis -d ../Results/WuttagoonaspisEurycaraspis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Eusthenopteron.txt -H ../Data2/Guiyu.txt -o ../Results/GuiyuEusthenopteron -d ../Results/GuiyuEusthenopteron.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Lunaspis.txt -H ../Data2/Eusthenopteron.txt -o ../Results/LunaspisEusthenopteron -d ../Results/LunaspisEusthenopteron.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Meemannia.txt -H ../Data2/Eusthenopteron.txt -o ../Results/MeemanniaEusthenopteron -d ../Results/MeemanniaEusthenopteron.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Eusthenopteron.txt -H ../Data2/Moythomasia.txt -o ../Results/MoythomasiaEusthenopteron -d ../Results/MoythomasiaEusthenopteron.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Romundina.txt -H ../Data2/Eusthenopteron.txt -o ../Results/RomundinaEusthenopteron -d ../Results/RomundinaEusthenopteron.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Wuttagoonaspis.txt -H ../Data2/Eusthenopteron.txt -o ../Results/WuttagoonaspisEusthenopteron -d ../Results/WuttagoonaspisEusthenopteron.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Lunaspis.txt -H ../Data2/Guiyu.txt -o ../Results/LunaspisGuiyu -d ../Results/LunaspisGuiyu.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Meemannia.txt -H ../Data2/Guiyu.txt -o ../Results/MeemanniaGuiyu -d ../Results/MeemanniaGuiyu.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Moythomasia.txt -H ../Data2/Guiyu.txt -o ../Results/MoythomasiaGuiyu -d ../Results/MoythomasiaGuiyu.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Romundina.txt -H ../Data2/Guiyu.txt -o ../Results/RomundinaGuiyu -d ../Results/RomundinaGuiyu.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Wuttagoonaspis.txt -H ../Data2/Guiyu.txt -o ../Results/WuttagoonaspisGuiyu -d ../Results/WuttagoonaspisGuiyu.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Meemannia.txt -H ../Data2/Lunaspis.txt -o ../Results/MeemanniaLunaspis -d ../Results/MeemanniaLunaspis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Lunaspis.txt -H ../Data2/Moythomasia.txt -o ../Results/MoythomasiaLunaspis -d ../Results/MoythomasiaLunaspis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Lunaspis.txt -H ../Data2/Romundina.txt -o ../Results/RomundinaLunaspis -d ../Results/RomundinaLunaspis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Wuttagoonaspis.txt -H ../Data2/Lunaspis.txt -o ../Results/WuttagoonaspisLunaspis -d ../Results/WuttagoonaspisLunaspis.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Meemannia.txt -H ../Data2/Moythomasia.txt -o ../Results/MoythomasiaMeemannia -d ../Results/MoythomasiaMeemannia.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Meemannia.txt -H ../Data2/Romundina.txt -o ../Results/RomundinaMeemannia -d ../Results/RomundinaMeemannia.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Meemannia.txt -H ../Data2/Wuttagoonaspis.txt -o ../Results/WuttagoonaspisMeemannia -d ../Results/WuttagoonaspisMeemannia.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Romundina.txt -H ../Data2/Moythomasia.txt -o ../Results/RomundinaMoythomasia -d ../Results/RomundinaMoythomasia.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Wuttagoonaspis.txt -H ../Data2/Moythomasia.txt -o ../Results/WuttagoonaspisMoythomasia -d ../Results/WuttagoonaspisMoythomasia.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
./magnapp_cli_linux64 -G ../Data2/Wuttagoonaspis.txt -H ../Data2/Romundina.txt -o ../Results/WuttagoonaspisRomundina -d ../Results/WuttagoonaspisRomundina.txt -m S3 -p 100 -t 10 -a 0.5 -n 100 -f 1
